appname: srv-greeter
listen: ":18001"
registryListen: ":18001"
appmode: prod
log:
  file:
    filename: runtime/greeter.log
    maxsize: 100
    level: 1 #debug:-1;info:0;warning:1;error:2;DPanic:3;Panic:4;Fatal:5

error-template: config/errors.zh.yaml

#db:
#  default:
#    dialect: mysql
#    dsn: root:@tcp(localhost:3306)/yak

jwt:
  enable: false
  public-key: "" # pem file if use rs algorithm
  encryption-key: "abcderf"

auth:
  auth-server: ""
  check-access: ""
  check-access-timeout: 1000 #microsecond
  router-prefix: ""

#opentracing:
#  sampler:
#    type: const
#    param: 1
#  reporter:
#    logSpans: false
#    localAgentHostPort: "127.0.0.1:6831"
#  headers:
#    TraceContextHeaderName: trace.traceid


metrics:
  enable: false
  backend: prometheus